fetcher_defaults:
  max_retries: 5
  timeout: 30

sink_defaults:
  db_url: sqlite+aiosqlite:///scraper.db

services:
  - name: fi_shortinterest
    fetcher: FiFetcher
    parsers: [FiAggParser, FiActParser, DiffParser]
    sinks: [DatabaseSink, DiscordSink]
    schedule: "0,30 * * * *"  # every half hour
    
# Environment and configuration
discord:
  channel_id: 1175019650963222599
  error_channel_id: 1162053416290361516
  tracked_companies:
    - "Embracer Group AB"
    - "Paradox Interactive AB (publ)"
    - "Starbreeze AB"
    - "EG7"
    - "Enad Global 7"
    - "Maximum Entertainment"
    - "MAG Interactive"
    - "G5 Entertainment AB (publ)"
    - "Modern Times Group MTG AB"
    - "Thunderful"
    - "MGI - Media and Games Invest SE"
    - "Stillfront Group AB (publ)"