# Example pipeline configuration with Discord sink integration
pipelines:
  # FI Short Interest with Discord notification
  fi_shortinterest_with_discord:
    schedule:
      cron: "0 */2 * * *"  # Every 2 hours
    chain:
      - class: fi_shortinterest.FiFetcher
        kwargs: {}
      - class: fi_shortinterest.FiAggParser
        kwargs: {}
      - class: fi_shortinterest.DiffParser
        kwargs:
          db_path: "fi_shortinterest.db"
      - class: fi_shortinterest.DatabaseSink
        kwargs:
          db_path: "fi_shortinterest.db"
      # Add Discord sink for notifications (requires DISCORD_TOKEN and bot setup)
      # - class: core.infra.discord_sink.DiscordSink
      #   kwargs:
      #     channel_id: 1234567890123456789  # Replace with your Discord channel ID

  # Manual test pipeline for Discord
  discord_test_pipeline:
    chain:
      - class: fi_shortinterest.FiFetcher
        kwargs: {}
      - class: fi_shortinterest.FiAggParser
        kwargs: {}
      # Add Discord sink for testing (uncomment when you have a Discord bot set up)
      # - class: core.infra.discord_sink.DiscordSink
      #   kwargs:
      #     channel_id: 1234567890123456789  # Replace with your Discord channel ID
