pipelines:
  # FI Short Interest - Aggregate data pipeline with diff detection
  # Runs every 10 minutes
  fi_shortinterest_agg:
    schedule:
      interval:
        minutes: 10  # Every 10 minutes
    chain:
      - class: fi_shortinterest.FiFetcher
        kwargs: {}
      - class: fi_shortinterest.FiAggParser
        kwargs: {}
      - class: fi_shortinterest.DiffParser
        kwargs:
          db_path: "fi_shortinterest.db"
      - class: fi_shortinterest.DatabaseSink
        kwargs:
          db_path: "fi_shortinterest.db"

  # FI Short Interest - Position data pipeline with diff detection
  # Runs every 10 minutes
  fi_shortinterest_pos:
    schedule:
      interval:
        minutes: 10  # Every 10 minutes
    chain:
      - class: fi_shortinterest.FiFetcher
        kwargs: {}
      - class: fi_shortinterest.FiActParser
        kwargs: {}
      - class: fi_shortinterest.DiffParser
        kwargs:
          db_path: "fi_shortinterest.db"
      - class: fi_shortinterest.DatabaseSink
        kwargs:
          db_path: "fi_shortinterest.db"

  # TCGPlayer - Pokemon sets CSV data pipeline
  # Runs at 9 PM every day
  tcgplayer_pokemon_sets:
    schedule:
      cron: "0 21 * * *"  # Daily at 9 PM (21:00)
    chain:
      - class: tcgplayer.PokemonSetsCsvFetcher
        kwargs:
          csv_path: "development/tcg/pokemon_sets.csv"
      - class: tcgplayer.PokemonSetsParser
      - class: tcgplayer.TcgDatabaseSink
        kwargs:
          db_path: "tcg.db"

  # TCGPlayer - Price history data pipeline
  # Runs at 9 PM every day
  tcgplayer_price_history:
    schedule:
      cron: "0 21 * * *"  # Daily at 9 PM (21:00)
    chain:
      - class: tcgplayer.TcgPlayerPriceHistoryFetcher
        kwargs:
          db_path: "tcg.db"
          delay_seconds: 2.0
      - class: tcgplayer.PriceHistoryParser
      - class: tcgplayer.TcgDatabaseSink
        kwargs:
          db_path: "tcg.db"

  # AppMagic - Companies data pipeline
  # Runs every minute
  appmagic_companies:
    schedule:
      interval:
        minutes: 1
    chain:
      - class: appmagic.AppMagicFetcher
        kwargs:
          companies:
            - name: "Zynga"
              ticker: "TTWO"
              store: 1
              store_publisher_id: "6690081412016968981"
            - name: "Crazylabs"
              ticker: "EMBRAC"
              store: 1
              store_publisher_id: "6443412597262225303"
            - name: "G5 Entertainment"
              ticker: "G5"
              store: 1
              store_publisher_id: "8053728788464134315"
            - name: "Mag Interactive"
              ticker: "MAGI"
              store: 1
              store_publisher_id: "6558349509091194327"
            - name: "Bytro Labs"
              ticker: "SF"
              store: 2
              store_publisher_id: "1287077622"
            - name: "Big Blue Bubble"
              ticker: "EG7"
              store: 1
              store_publisher_id: "6388759014800755560"
            - name: "Plarium Global"
              ticker: "MTG"
              store: 1
              store_publisher_id: "5766366711041032164"
            - name: "Electronic Arts"
              ticker: "EA"
              store: 1
              store_publisher_id: "6605125519975771237"

      - class: appmagic.AppMagicParser
        kwargs: {}
      - class: appmagic.AppMagicSink
        kwargs:
          db_path: "mobile_analytics.db"