# Pipeline configuration with scheduling support
pipelines:
  # FI Short Interest - Aggregate data pipeline with diff detection
  # Runs every hour during market hours (Stockholm timezone)
  fi_shortinterest_agg:
    schedule:
      cron: "0 9-17 * * 1-5"  # Every hour from 9 AM to 5 PM, Monday to Friday
    chain:
      - class: fi_shortinterest.FiFetcher
        kwargs: {}
      - class: fi_shortinterest.FiAggParser
        kwargs: {}
      - class: fi_shortinterest.DiffParser
        kwargs:
          db_path: "fi_shortinterest.db"
      - class: fi_shortinterest.DatabaseSink
        kwargs:
          db_path: "fi_shortinterest.db"

  # FI Short Interest - Position data pipeline with diff detection
  # Runs every 30 minutes during market hours
  fi_shortinterest_pos:
    schedule:
      cron: "*/30 9-17 * * 1-5"  # Every 30 minutes from 9 AM to 5 PM, Monday to Friday
    chain:
      - class: fi_shortinterest.FiFetcher
        kwargs: {}
      - class: fi_shortinterest.FiActParser
        kwargs: {}
      - class: fi_shortinterest.DiffParser
        kwargs:
          db_path: "fi_shortinterest.db"
      - class: fi_shortinterest.DatabaseSink
        kwargs:
          db_path: "fi_shortinterest.db"

  # TCGPlayer - Pokemon sets CSV data pipeline
  # Runs once per day at 2 AM
  tcgplayer_pokemon_sets:
    schedule:
      cron: "0 2 * * *"  # Daily at 2 AM
    chain:
      - class: tcgplayer.PokemonSetsCsvFetcher
        kwargs:
          csv_path: "development/tcg/pokemon_sets.csv"
      - class: tcgplayer.PokemonSetsParser
      - class: tcgplayer.TcgDatabaseSink
        kwargs:
          db_path: "tcg.db"

  # TCGPlayer - Price history data pipeline
  # Runs every 6 hours with interval scheduling
  tcgplayer_price_history:
    schedule:
      interval:
        hours: 6
    chain:
      - class: tcgplayer.TcgPlayerPriceHistoryFetcher
        kwargs:
          db_path: "tcg.db"
          delay_seconds: 2.0
      - class: tcgplayer.PriceHistoryParser
      - class: tcgplayer.TcgDatabaseSink
        kwargs:
          db_path: "tcg.db"

  # Example pipeline without scheduling - runs once on startup
  manual_pipeline:
    chain:
      - class: fi_shortinterest.FiFetcher
        kwargs: {}
      - class: fi_shortinterest.FiAggParser
        kwargs: {}
      - class: fi_shortinterest.DatabaseSink
        kwargs:
          db_path: "fi_shortinterest.db"
